<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => '',
    'ID' => '',
    'Table' => 'Tabela',
    'Admin email' => 'Email administrator',
    'Agree - Marketing' => 'Zgoda - Marketing',
    'Agree - Terms and conditions' => 'Zgoda - Regulamin',
    'Check reCaptcha field' => 'Zaznacz pole reCaptcha',
    'Company' => 'Firma',
    'Contact form' => 'Formularz kontaktowy',
    'Contact form - Settings' => 'Formularz kontaktowy - Ustawienia',
    'Created At' => 'Data utworzenia',
    'Form Settings ID' => 'ID Ustawienia formularza',
    'Forms' => 'Formularze',
    'From email' => 'Od email',
    'From name' => 'Od nazwa',
    'General' => 'Główne',
    'Language' => 'Język',
    'Name' => 'Nazwa',
    'Phone' => 'Telefon',
    'Please accept terms and conditions' => 'Proszę zaakceptować regulamin',
    'Recipient' => 'Odbiorca',
    'Send email' => 'Wyślij email',
    'Separate by comma' => 'Oddziel przecinkami',
    'Subject' => 'Temat',
    'Tags' => 'Tagi',
    'Text' => 'Tekst',
    'Thanks text' => 'Tekst podziękowania',
    'Type' => 'Typ',
    'User email' => 'Email użytkownik',
    'reCaptcha' => 'reCaptcha',
];
